## SQL config
spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/myExpenses
spring.r2dbc.username=root
spring.r2dbc.password=123
spring.r2dbc.initialization-mode=always

# My custom JWT token keystore (For sure for prod this is not the same :))
jwt-token.keystore-path=C:/E/workspace/demo-project/backend/security/src/test/resources/jwt-token-dev.ks
jwt-token.keystore-password=password

# Email configuration used to send the activation email
spring.mail.host=smtp.example.com
spring.mail.port=25
spring.mail.username=setusername
spring.mail.password=setpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true