name: Build app

on: [push]

jobs:
  compile-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: false  # Set process.env.CI to false
    steps:
    - uses: actions/checkout@v3
    - name: Set up NPM
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install --force  # We shouldn't use force. Is just because some conflicts in the libs that need to be solved.
      working-directory: ./frontendv2
    - name: Build with npm
      run: npm run build 
      working-directory: ./frontendv2
  compile-backend:
    needs: compile-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./backend

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
