name: Build the app and create binary.

on: [push]

jobs:
  compile-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: false  # Set process.env.CI to false
    steps:
    - uses: actions/checkout@v3
    - name: Set up NPM
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install --force  # We shouldn't use force. Is just because some conflicts in the libs that need to be solved.
      working-directory: ./frontendv2
    - name: Build with npm
      run: npm run build 
      working-directory: ./frontendv2
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend-artifacts
        path: ./frontendv2/build
  compile-backend:
    needs: compile-frontend
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    - name: Get last version
      id: get_last_version
      run: ./getVersion.sh
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend-artifacts
        path: ./backend/src/main/resources/META-INF/resources
    - name: Check files updated
      run: ls -lht
      working-directory: ./backend/src/main/resources/META-INF/resources
    - name: Set Maven version
      run: mvn versions:set -DnewVersion=$NEXT_TAG
      working-directory: ./backend
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
      working-directory: ./backend
    - name: List compiled files
      run: ls -lht ./backend/target/
    - name: Creating tag
      run: ./tagRepo.sh
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{env.NEXT_TAG}}
        name: Demo-project ${{env.NEXT_TAG}}
        files: ./backend/target/*.jar
